apiVersion: v1
kind: Service
metadata:
  name: bigtable-autoscaler
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: bigtable-autoscaler
spec:
  # Required for Container Engine Ingress:
  # https://github.com/kubernetes/ingress/tree/master/controllers/gce
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app: bigtable-autoscaler
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bigtable-autoscaler 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigtable-autoscaler 
  template:
    metadata:
      labels:
        app: bigtable-autoscaler 
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    spec:
      containers:
      - name: bigtable-autoscaler 
        image: {{IMAGE}}
        volumeMounts:
          - mountPath: /service-account
            name: service-account
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            memory: 512Mi
        env:
          - name: ENVIRONMENT
            value: remote
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /service-account/recommendationsvc.json
          # - name: JDBC_URL
          #   value: jdbc:postgresql://postgres:5432/autoscaler
          # - name: DB_USERNAME
          #   value: postgres
          # - name: DB_PASSWORD
          #   value: postgres
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - all
      volumes:
      - name: service-account
        secret:
          secretName: recommendationsvc-key
