# tag the image with both :date-commit and :commit
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
    '--tag', '$_REPO/$PROJECT_ID/$_DOCKER_TAG_DATE_COMMIT',
    '--tag', '$_REPO/$PROJECT_ID/$_DOCKER_TAG_COMMIT',
    '.']
images: [$_REPO/$PROJECT_ID/$_DOCKER_TAG_DATE_COMMIT, $_REPO/$PROJECT_ID/$_DOCKER_TAG_COMMIT]

# To avoid giving general 'Viewer' permission to the service account that builds the image
# we create a storage bucket and manage permissions on that storage bucket
# https://github.com/GoogleCloudPlatform/cloud-builders/issues/120
logsBucket: 'gs://container_build_logs_tm'

# the bluecore cloudbuild template supplies lots of substitutions we don't use
options:
  substitution_option: 'ALLOW_LOOSE'
