version: 2
jobs:
  build:
    docker:
      - image: docker:19.03
    working_directory: ~/bigtable-autoscaler
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Make
          command: |
            apt-get update && apt-get install make
      - run:
          name: Build image
          command: SERVICE_IMAGE_VERSION=$CIRCLE_SHA1 make build-image
      - run:
          name: Upload image
          command: |
            if [ $CIRCLE_BRANCH == "master" ]; then
              echo $TRIGGERMAIL_GCR_AUTH > ${HOME}/gcloud-service-key.json
              gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
              docker tag $CIRCLE_SHA1 us.gcr.io/triggeredmail/bigtable-autoscaler:$CIRCLE_SHA1
              docker push us.gcr.io/triggeredmail/bigtable-autoscaler:$CIRCLE_SHA1
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: build-global